FROM node:18 as builder
ENV NODE_ENV production

WORKDIR /app

COPY package.json .
RUN npm i

COPY . .

RUN npm run build

FROM node:18

WORKDIR /usr/src/app

RUN npm install -g serve

COPY --from=builder /app/dist ./build